### ISSUE TITLE
Update PlayerWeaponComponent.kt to use FXGL local timer

### ISSUE THREAD

**Issue by AlmasB** [AahzBrut/GalaxyShooter#8]
`System.currentTimeMillis()` calls return real time, which advances even if the game is paused or in a different scene. For the gameplay, game time, which is driven by the engine, should be used. Furthermore, game time is less susceptible to CPU performance fluctuations.

[Simple example of local timer](https://github.com/AlmasB/FXGL/blob/master/fxgl/src/main/kotlin/com/almasb/fxgl/dsl/components/IntervalSwitchComponent.kt#L21)

**Comment by AahzBrut** [comment]
Thanks!
